export const cocktails = [
    {
        id: 1,
        name: 'Old Fashioned',
        // image: 'oldFashioned.jpg',
        description: 'A strong bourbon drink',
        category: 'strong',
        price: 8,
        ingredients: 'Bourbon, simple syrup, bitters. Garnish: orange peel, maraschino cherry',
    },
    {
        id: 2,
        name: 'White Russian',
        // image: 'whiteRussian.jpg',
        description: 'A creamy vodka drink',
        category: 'creamy',
        price: 9,
        ingredients: 'Vodka, coffee liqueur, half and half',
    },
    {
        id: 3,
        name: 'French 75',
        // image: 'french75.jpeg',
        description: 'A gin and champagne drink',
        category: 'bubbles',
        price: 11,
        ingredients: 'Gin, lemon juice, simple syrup, champagne. Garnish: lemon twist',
    },
    {
        id: 4,
        name: 'Mojito',
        // image: 'mojito.jpg',
        description: 'A refreshing rum drink',
        category: 'refreshing',
        price: 10,
        ingredients: 'White rum, mint, lime, simple syrup, club soda. Garnish: lime wedge, mint',
    },
    {
        id: 5,
        name: 'Cadillac Margarita',
        // image: 'margarita.png',
        description: 'A strong tequila drink',
        category: 'strong',
        price: 9,
        ingredients: 'Tequila, orange liqueur, lime juice. Garnish: lime slice',
    },
    {
        id: 6,
        name: 'Gimlet',
        // image: 'gimlet.png',
        description: 'A refreshing gin and lime drink',
        category: 'refreshing',
        price: 8,
        ingredients: 'Gin, lime juice, simple syrup. Garnish: lime wheel',
    },
    {
        id: 7,
        name: 'Martini',
        // image: 'martini.png',
        description: 'A strong gin drink',
        category: 'strong',
        price: 11,
        ingredients: 'Gin, dry vermouth. Garnish: olives or lemon twist',
    }
    {
        id: 8,
        name: 'Greyhound',
        // image: 'greyhound.png',
        description: 'A refreshing vodka drink',
        category: 'refreshing',
        price: 7,
        ingredients: 'Vodka, grapefruit juice. Garnish: grapefruit wedge',
    }
];